generators:
  /webpack/id: {}
  /webpack:
    keys:
      - id
  /readme/id: {}
  /readme:
    keys:
      - id
specs:
  /app/title: {}
  /app:
    keys:
      - name
      - title
      - description
  /app/description: {}
