generators:
  /webpack/id: {}
  /webpack:
    keys:
      - id
  /readme/id: {}
  /readme:
    keys:
      - id
  /react/id: {}
  /react:
    keys:
      - id
specs:
  /app/title: {}
  /app:
    keys:
      - title
      - name
      - version
      - description
  /app/description: {}
  /app/version: {}
  /:
    keys:
      - app
      - dependencies
